name: 'Test ARM64'
on:
  workflow_dispatch:

jobs:
  armv64_job:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Info
        run: uname -a

      - name: Add libzstd
        shell: bash
        run: echo sudo apt-get install -y libzstd-dev

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x

      - name: Build
        run: |
          set -x
          echo apt-get update -q
          echo apt-get install -q -y --no-install-recommends curl libzstd-dev libicu-dev ca-certificates dotnet-sdk-7.0
          cd src
          dotnet --list-sdks
          dotnet build -c Release
          dotnet test -c Release
