name: 'Test ARM64'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "asf-arm"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        shell: bash
        run: sudo apt-get install -y libzstd-dev libicu-dev

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Cache Nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: |
          dotnet build -c Release src/
          dotnet run -c Release --project src/
