name: 'Test ARM64'
on:
  workflow_dispatch:

jobs:
  armv64_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            set -x
            apt-get update -q
            apt-get install -q -y --no-install-recommends curl libzstd-dev libicu-dev ca-certificates dotnet-sdk-7.0
            cd src
            dotnet build -c Release
            dotnet test -c Release
