name: 'Test Multi OS'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        config: [Debug, Release]
        include:
          - os: macos-14
            config: Debug

    steps:
      - uses: actions/checkout@v4

      - name: Info
        run: |
          echo ${{matrix.os}}
          echo ${{matrix.config}}
          uname -a

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Build
        run: |
          dotnet --list-sdks
          dotnet build -c ${{ matrix.config }} src/

      - name: Run
        run: |
          dotnet run -c ${{ matrix.config }} --project src/
