name: 'Test ARM64'
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: src
    
jobs:
  build:
    strategy:
      matrix:
        target:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - ['self-hosted', 'asf-arm']

    runs-on: ${{ matrix.target}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0.x

      - name: Cache NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: |
          dotnet build -c Release

      - name: Run
        run: |
          dotnet run -c Release
